version: '3.4'

services:
  server:
    image: gcavalcante8808/k3s-docker:latest
    build: 
      context: .
      args:
        K3S_VERSION: ${K3S_VERSION:-v1.18.6+k3s1}
    privileged: true
    environment:
    - K3S_TOKEN=${K3S_TOKEN:-$(openssl rand -hex 32)}
    - K3S_KUBECONFIG_OUTPUT=${K3S_KUBECONFIG_OUTPUT:-/output/kubeconfig.yaml}
    - K3S_KUBECONFIG_MODE=${K3S_KUBECONFIG_MODE:-666}
    - KUBECONFIG=${K3S_KUBECONFIG_OUTPUT:-/output/kubeconfig.yaml}
    volumes:
    - ./output:/output
    ports:
    - 6443:6443
